# Generated by Django 4.2.14 on 2024-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToGetConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'email для получения подтверждения заказа.',
                'verbose_name_plural': 'Email-ы для получения подтверждения заказа.',
                'ordering': ('id',),
            },
        ),
    ]
