# Generated by Django 4.2.14 on 2024-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',), 'verbose_name': 'корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
