# Generated by Django 4.2.14 on 2024-07-27 05:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('delivery_address_lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Ширина')),
                ('delivery_address_lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('delivery_type', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовызов')], max_length=10, verbose_name='Тип заказа')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказаы',
            },
        ),
    ]
