# Generated by Django 4.2.14 on 2024-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказаы'},
        ),
    ]
