# Generated by Django 4.2.14 on 2024-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_is_accepted_order_is_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dishes',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='Для работы сериализатора'),
        ),
    ]
