# Generated by Django 4.2.14 on 2024-07-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_dishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.TextField(editable=False, verbose_name='Для работы сериализатора'),
        ),
    ]
