# Generated by Django 4.2.14 on 2024-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=6, verbose_name='Общая цена'),
            preserve_default=False,
        ),
    ]
