# Generated by Django 4.2.14 on 2024-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id',), 'verbose_name': 'заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
