# Generated by Django 4.2.14 on 2024-08-03 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_cart_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address_lng',
        ),
    ]
