# Generated by Django 4.2.14 on 2024-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=512, verbose_name='Адрес')),
                ('working_hours', models.TextField(max_length=512, verbose_name='Часы работы')),
                ('phones', models.TextField(max_length=512, verbose_name='Телефонные номера')),
                ('delivery_cost', models.TextField(blank=True, max_length=512, null=True, verbose_name='Политика доставки')),
                ('delivery_time', models.TextField(blank=True, max_length=512, null=True, verbose_name='Время доставки')),
                ('payment_methods', models.TextField(blank=True, max_length=512, null=True, verbose_name='Способы оплаты')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='Whatsapp ссылка')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram ссылка')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram ссылка')),
            ],
            options={
                'verbose_name': 'информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
    ]
