# Generated by Django 4.2.14 on 2024-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'ordering': ('id',), 'verbose_name': 'информация о компании', 'verbose_name_plural': 'Информация о компании'},
        ),
    ]
