# Generated by Django 4.2.14 on 2024-07-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Идентификатор должен быть позож на имя категории, но на английском языке.', unique=True, verbose_name='Идентификатор')),
                ('is_on_main', models.BooleanField(default=False, verbose_name='Добавить на главную страницу?')),
                ('image', models.ImageField(upload_to='categories_photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Ставтьте значение в этом поле только в том случае если хотите чтобы был эффект скидки. Т.е эта цена на сайте будет зачёркнута. Если не хотите такого, просто оставьте это поле пустым.', max_digits=6, null=True, verbose_name='Цена без скидки')),
                ('image', models.ImageField(upload_to='dishes_photos/', verbose_name='Фото')),
                ('is_on_main', models.BooleanField(default=False, verbose_name='Добавить на главную страницу?')),
                ('is_new', models.BooleanField(default=False, verbose_name='Добавить в раздел новые?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='product.category', verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
