# Generated by Django 4.2.14 on 2024-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='categories_photos/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
