# Generated by Django 4.2.14 on 2024-07-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_dish_category_dish_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('id',), 'verbose_name': 'блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
