# Generated by Django 4.2.14 on 2024-07-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories_photos/dish_default.jpg', upload_to='categories_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='dishes_photos/dish_default.jpg', upload_to='dishes_photos/', verbose_name='Фото'),
        ),
    ]
