# Generated by Django 4.2.14 on 2024-07-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_image_alter_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ставтьте значение в этом поле только в том случае если хотите чтобы был эффект скидки. Т.е эта цена на сайте будет зачёркнута. Если не хотите такого, просто оставьте это поле пустым.', max_digits=6, null=True, verbose_name='Цена без скидки'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(upload_to='dishes_photos/', verbose_name='Фото'),
        ),
    ]
