# Generated by Django 4.2.14 on 2024-07-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_alter_dish_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default=10, max_length=6144, verbose_name='Описание блюда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Вес в граммах'),
            preserve_default=False,
        ),
    ]
