# Generated by Django 4.2.14 on 2024-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_dish_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category',
            new_name='categories',
        ),
    ]
